-- ==========================================
-- Wasel Platform - Seed Data
-- 27 Centers across all Egyptian governorates
-- ==========================================

INSERT INTO centers (name_ar, name_en, city_ar, city_en, region_ar, region_en, address_ar, address_en, phone, working_hours_ar, working_hours_en, services, insurance_supported, supported_insurers, images, is_active) VALUES
('واصل - المركز الرئيسي', 'Wasel - Main Center', 'القاهرة', 'Cairo', 'القاهرة الكبرى', 'Greater Cairo', 'شارع التحرير، وسط البلد', 'Tahrir St, Downtown', '02-123-4567', 'السبت - الخميس: 9 صباحاً - 9 مساءً', 'Sat-Thu: 9AM-9PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"},{"name_ar":"أحذية طبية","name_en":"Medical Shoes"}]', true, '{"ميتلايف","أكسا","مصر للتأمين"}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - الجيزة', 'Wasel - Giza', 'الجيزة', 'Giza', 'القاهرة الكبرى', 'Greater Cairo', 'شارع الهرم، الجيزة', 'Haram St, Giza', '02-234-5678', 'السبت - الخميس: 9 صباحاً - 8 مساءً', 'Sat-Thu: 9AM-8PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', true, '{"ميتلايف","بوبا"}', '{"https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600"}', true),
('واصل - الإسكندرية', 'Wasel - Alexandria', 'الإسكندرية', 'Alexandria', 'الإسكندرية', 'Alexandria', 'شارع الكورنيش، سموحة', 'Corniche St, Smouha', '03-456-7890', 'السبت - الخميس: 10 صباحاً - 8 مساءً', 'Sat-Thu: 10AM-8PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"},{"name_ar":"تأهيل حركي","name_en":"Rehabilitation"}]', true, '{"أكسا","أليانز"}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true),
('واصل - المنصورة', 'Wasel - Mansoura', 'المنصورة', 'Mansoura', 'الدلتا', 'Delta', 'شارع الجمهورية', 'El Gomhouria St', '050-123-4567', 'السبت - الخميس: 9 صباحاً - 9 مساءً', 'Sat-Thu: 9AM-9PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', true, '{"مصر للتأمين"}', '{"https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600"}', true),
('واصل - طنطا', 'Wasel - Tanta', 'طنطا', 'Tanta', 'الدلتا', 'Delta', 'شارع البحر', 'El Bahr St', '040-123-4567', 'السبت - الخميس: 9 صباحاً - 8 مساءً', 'Sat-Thu: 9AM-8PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"},{"name_ar":"أحذية طبية","name_en":"Medical Shoes"}]', false, '{}', '{"https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600"}', true),
('واصل - أسيوط', 'Wasel - Assiut', 'أسيوط', 'Assiut', 'الصعيد', 'Upper Egypt', 'شارع الجمهورية', 'El Gomhouria St', '088-123-4567', 'السبت - الخميس: 9 صباحاً - 8 مساءً', 'Sat-Thu: 9AM-8PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', true, '{"مصر للتأمين"}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true),
('واصل - سوهاج', 'Wasel - Sohag', 'سوهاج', 'Sohag', 'الصعيد', 'Upper Egypt', 'شارع الكورنيش', 'Corniche St', '093-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - الأقصر', 'Wasel - Luxor', 'الأقصر', 'Luxor', 'الصعيد', 'Upper Egypt', 'شارع المحطة', 'Station St', '095-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600"}', true),
('واصل - أسوان', 'Wasel - Aswan', 'أسوان', 'Aswan', 'الصعيد', 'Upper Egypt', 'شارع السوق', 'Market St', '097-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600"}', true),
('واصل - الزقازيق', 'Wasel - Zagazig', 'الزقازيق', 'Zagazig', 'الدلتا', 'Delta', 'شارع الجلاء', 'El Galaa St', '055-123-4567', 'السبت - الخميس: 9 صباحاً - 8 مساءً', 'Sat-Thu: 9AM-8PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"},{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', true, '{"ميتلايف"}', '{"https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600"}', true),
('واصل - بنها', 'Wasel - Banha', 'بنها', 'Banha', 'الدلتا', 'Delta', 'شارع فريد ندا', 'Farid Nada St', '013-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - المنيا', 'Wasel - Minya', 'المنيا', 'Minya', 'الصعيد', 'Upper Egypt', 'شارع الكورنيش', 'Corniche St', '086-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true),
('واصل - بني سويف', 'Wasel - Beni Suef', 'بني سويف', 'Beni Suef', 'الصعيد', 'Upper Egypt', 'شارع صلاح سالم', 'Salah Salem St', '082-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600"}', true),
('واصل - الفيوم', 'Wasel - Fayoum', 'الفيوم', 'Fayoum', 'الصعيد', 'Upper Egypt', 'شارع الجمهورية', 'El Gomhouria St', '084-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600"}', true),
('واصل - دمياط', 'Wasel - Damietta', 'دمياط', 'Damietta', 'الدلتا', 'Delta', 'شارع الكورنيش', 'Corniche St', '057-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600"}', true),
('واصل - بورسعيد', 'Wasel - Port Said', 'بورسعيد', 'Port Said', 'القناة', 'Canal', 'شارع محمد علي', 'Mohamed Ali St', '066-123-4567', 'السبت - الخميس: 9 صباحاً - 8 مساءً', 'Sat-Thu: 9AM-8PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"},{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', true, '{"أكسا"}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - الإسماعيلية', 'Wasel - Ismailia', 'الإسماعيلية', 'Ismailia', 'القناة', 'Canal', 'شارع الثورة', 'El Thawra St', '064-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true),
('واصل - السويس', 'Wasel - Suez', 'السويس', 'Suez', 'القناة', 'Canal', 'شارع الجيش', 'El Geish St', '062-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600"}', true),
('واصل - كفر الشيخ', 'Wasel - Kafr El Sheikh', 'كفر الشيخ', 'Kafr El Sheikh', 'الدلتا', 'Delta', 'شارع صلاح سالم', 'Salah Salem St', '047-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600"}', true),
('واصل - المنوفية', 'Wasel - Menoufia', 'شبين الكوم', 'Shebin El Kom', 'الدلتا', 'Delta', 'شارع جمال عبد الناصر', 'Gamal St', '048-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600"}', true),
('واصل - البحيرة', 'Wasel - Beheira', 'دمنهور', 'Damanhour', 'الدلتا', 'Delta', 'شارع الجمهورية', 'El Gomhouria St', '045-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - قنا', 'Wasel - Qena', 'قنا', 'Qena', 'الصعيد', 'Upper Egypt', 'شارع بورسعيد', 'Port Said St', '096-123-4567', 'السبت - الخميس: 9 صباحاً - 7 مساءً', 'Sat-Thu: 9AM-7PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true),
('واصل - مطروح', 'Wasel - Matrouh', 'مرسى مطروح', 'Marsa Matrouh', 'الساحل', 'Coast', 'شارع الكورنيش', 'Corniche St', '046-123-4567', 'السبت - الخميس: 10 صباحاً - 6 مساءً', 'Sat-Thu: 10AM-6PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600"}', true),
('واصل - الوادي الجديد', 'Wasel - New Valley', 'الخارجة', 'Kharga', 'الصعيد', 'Upper Egypt', 'شارع جمال عبد الناصر', 'Gamal St', '092-123-4567', 'السبت - الخميس: 9 صباحاً - 6 مساءً', 'Sat-Thu: 9AM-6PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600"}', true),
('واصل - البحر الأحمر', 'Wasel - Red Sea', 'الغردقة', 'Hurghada', 'البحر الأحمر', 'Red Sea', 'شارع الشيراتون', 'Sheraton St', '065-123-4567', 'السبت - الخميس: 10 صباحاً - 6 مساءً', 'Sat-Thu: 10AM-6PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600"}', true),
('واصل - شمال سيناء', 'Wasel - North Sinai', 'العريش', 'El Arish', 'سيناء', 'Sinai', 'شارع 23 يوليو', '23rd July St', '068-123-4567', 'السبت - الخميس: 9 صباحاً - 6 مساءً', 'Sat-Thu: 9AM-6PM', '[{"name_ar":"أطراف صناعية","name_en":"Prosthetics"}]', false, '{}', '{"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600"}', true),
('واصل - جنوب سيناء', 'Wasel - South Sinai', 'شرم الشيخ', 'Sharm El Sheikh', 'سيناء', 'Sinai', 'خليج نعمة', 'Naama Bay', '069-123-4567', 'السبت - الخميس: 10 صباحاً - 6 مساءً', 'Sat-Thu: 10AM-6PM', '[{"name_ar":"جبائر طبية","name_en":"Orthoses"}]', false, '{}', '{"https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=600"}', true);

-- ==========================================
-- Devices Seed Data
-- ==========================================

INSERT INTO devices (name_ar, name_en, type, category, description_ar, description_en, price_range_min, price_range_max, manufacturer, specifications, is_active) VALUES
('طرف صناعي ميكانيكي تحت الركبة', 'Mechanical Below-Knee Prosthesis', 'prosthetic', 'below_knee', 'طرف صناعي تقليدي مناسب للنشاط المنخفض', 'Traditional prosthesis for low activity', 8000, 20000, 'Ottobock', '{"weight":"1.2kg","material":"Polypropylene"}', true),
('طرف صناعي هيدروليكي تحت الركبة', 'Hydraulic Below-Knee Prosthesis', 'prosthetic', 'below_knee', 'تحكم هيدروليكي متقدم للمشي الطبيعي', 'Advanced hydraulic control for natural gait', 25000, 60000, 'Ottobock', '{"weight":"1.5kg","material":"Carbon Fiber"}', true),
('طرف صناعي ميكانيكي فوق الركبة', 'Mechanical Above-Knee Prosthesis', 'prosthetic', 'above_knee', 'نظام ركبة ميكانيكي موثوق', 'Reliable mechanical knee system', 15000, 35000, 'Ossur', '{"weight":"2.5kg","material":"Aluminum"}', true),
('طرف صناعي إلكتروني فوق الركبة', 'Electronic Above-Knee Prosthesis', 'prosthetic', 'above_knee', 'ركبة إلكترونية ذكية مع مستشعرات', 'Smart electronic knee with sensors', 80000, 200000, 'Ottobock', '{"weight":"2.0kg","material":"Carbon Fiber","sensors":"Gyroscope + Accelerometer"}', true),
('جبيرة AFO ديناميكية', 'Dynamic AFO', 'orthotic', 'afo', 'دعم القدم والكاحل أثناء المشي', 'Ankle-foot support during walking', 3000, 8000, 'Wasel Custom', '{"material":"Polypropylene","type":"Dynamic"}', true),
('جبيرة AFO مفصلية', 'Articulated AFO', 'orthotic', 'afo', 'مفصل كاحل يسمح بحركة طبيعية', 'Ankle joint allows natural motion', 5000, 15000, 'Wasel Custom', '{"material":"Carbon Composite","type":"Articulated"}', true),
('جبيرة KAFO', 'KAFO Brace', 'orthotic', 'kafo', 'دعم الركبة والكاحل والقدم', 'Knee-ankle-foot support', 8000, 25000, 'Wasel Custom', '{"material":"Steel + Leather","type":"Full leg"}', true),
('جبيرة عمود فقري TLSO', 'TLSO Spinal Brace', 'orthotic', 'spine', 'دعم الجذع والعمود الفقري', 'Trunk and spine support', 5000, 18000, 'Wasel Custom', '{"material":"Thermoplastic","coverage":"Thoraco-Lumbar"}', true),
('حذاء طبي مخصص', 'Custom Medical Shoe', 'accessory', 'shoes', 'حذاء مصمم حسب احتياجات القدم', 'Shoe designed per foot needs', 2000, 6000, 'Wasel Custom', '{"material":"Leather","insole":"Custom molded"}', true),
('نعل طبي مخصص', 'Custom Orthotic Insole', 'accessory', 'insoles', 'نعل داخلي لتصحيح المشي', 'Inner sole for gait correction', 800, 3000, 'Wasel Custom', '{"material":"EVA Foam","type":"Full length"}', true);
